<template>
  <v-container>
    <v-row class="text-center mb-6">
      <v-col cols="12">
        <h2 class="display-2">Experience</h2>
      </v-col>
    </v-row>
    
    <!-- Add Job Entry Button -->
    <v-btn small color="primary" class="rounded-circle" @click="showAddJobDialog = true">
      <v-icon>mdi-plus</v-icon>
    </v-btn>

    <!-- Add Job Dialog -->
    <v-dialog v-model="showAddJobDialog" max-width="600px">
      <v-card>
        <v-card-title>Add Job Entry</v-card-title>
        <v-card-text>
          <v-text-field v-model="newJob.title" label="Job Title"></v-text-field>
          <v-text-field v-model="newJob.years" label="Years"></v-text-field>
          <v-textarea v-model="newJob.description" label="Description"></v-textarea>
        </v-card-text>
        <v-card-actions>
          <v-btn color="blue darken-1" text @click="addJobEntry">Add</v-btn>
          <v-btn text @click="showAddJobDialog = false">Cancel</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
    
    <!-- Job Entries -->
    <v-card class="mb-4" v-for="(job, index) in jobExperiences" :key="index">
      <v-card-title>{{ job.title }}</v-card-title>
      <v-card-subtitle>{{ job.years }}</v-card-subtitle>
      <v-expand-transition>
        <v-card-text>
          <p>{{ job.description }}</p>
        </v-card-text>
      </v-expand-transition>
      <v-card-actions>
        <v-btn icon @click="removeJob(index)">
          <v-icon>mdi-close</v-icon>
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-container>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import Axios from 'axios';

interface JobExperience {
  id: number; // Assuming each job has an 'id' field
  title: string;
  years: string;
  description: string;
}

const jobExperiences = ref<JobExperience[]>([]);

const showAddJobDialog = ref(false);
const newJob = ref<JobExperience>({
  id: 0, // Initialize with 0 or null assuming Id is auto-generated by the server
  title: '',
  years: '',
  description: ''
});

// Fetch job experiences from API on component mount
onMounted(async () => {
  await fetchJobExperiences();
});

const fetchJobExperiences = async () => {
  try {
    const response = await Axios.get('/api/jobexperiences/GetJobExperiences');
    jobExperiences.value = response.data;
  } catch (error) {
    console.error('Error fetching job experiences:', error);
  }
};

const addJobEntry = async () => {
  try {
    const response = await Axios.post('/api/jobexperiences/PostJobExperiences', {
      id: 0,
      title: newJob.value.title,
      years: newJob.value.years,
      description: newJob.value.description
    }, {
      headers: {
        'Content-Type': 'application/json'
      }
    });

    jobExperiences.value.push(response.data); // Assuming API returns the added job experience with its Id
    newJob.value = { id: 0, title: '', years: '', description: '' }; // Clear inputs
    showAddJobDialog.value = false; // Close dialog
  } catch (error) {
    console.error('Error adding job entry:', error);
  }
};


const removeJob = async (index: number) => {
  const jobId = jobExperiences.value[index].id;
  try {
    await Axios.delete(`/api/jobexperiences/${jobId}`);
    jobExperiences.value.splice(index, 1);
  } catch (error) {
    console.error('Error removing job entry:', error);
  }
};
</script>

<style scoped>
/* Center text and add margin-bottom for spacing */
.text-center {
  text-align: center;
}

.mb-6 {
  margin-bottom: 3rem; /* Adjust as needed for spacing */
}

/* Style adjustments for job entries */
.v-card-title {
  font-size: 1.5rem;
  font-weight: bold;
}

.v-card-subtitle {
  font-size: 1rem;
  color: grey;
}

.v-expand-transition {
  max-height: 300px; /* Adjust max height for expand transition */
  overflow: hidden;
}

/* Circular button */
.rounded-circle {
  border-radius: 50%;
  width: 40px;
  height: 40px;
  min-width: 40px;
  min-height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>

